spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/Desafiojpa
    username: postgres
    password: romulo324
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
